### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by constantin50** [SMAPPNYU/youtube-data-api#31]
I want to receive the list of video's ids that are in the given playlist. I use get_videos_from_playlist_id(id), but there is a AttributeError.

```
vds = yt.get_videos_from_playlist_id(id)
Traceback (most recent call last):
  File "<pyshell#141>", line 1, in <module>
    vds = yt.get_videos_from_playlist_id(pls[2])
  File "C:\Python3\lib\site-packages\youtube_api\youtube_api.py", line 380, in get_videos_from_playlist_id
    timeout_in_n_seconds=20)
  File "C:\Python3\lib\site-packages\youtube_api\youtube_api.py", line 100, in _http_request
    with timeout(seconds=timeout_in_n_seconds):
  File "C:\Python3\lib\site-packages\youtube_api\youtube_api_utils.py", line 33, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

What it actually means and how to solve it?

Thank you!

**Comment by mabrownnyu** [comment]
I was unable to replicate this error. Please provide input details and python versions.
