### ISSUE TITLE
OverflowError: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by spanska** [SMAPPNYU/youtube-data-api#34]
**Describe the bug**
when using the lib on a 32bits env (raspberry pi), the following error occurs

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/server.py", line 11, in <module>
    import youtube
  File "/usr/src/app/youtube.py", line 9, in <module>
    from youtube_api import YoutubeDataApi
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/__init__.py", line 1, in <module>
    from youtube_api.youtube_api import YoutubeDataApi, YouTubeDataAPI
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/youtube_api.py", line 24, in <module>
    class YouTubeDataAPI:
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/youtube_api.py", line 580, in YouTubeDataAPI
    published_before=datetime.datetime.timestamp(datetime.datetime(3000,1,1)),
OverflowError: timestamp out of range for platform time_t

**Expected behavior**
no error should happen. In my opinion the date '3000' is too high on 32 bits env. Maybe setting it to 2038 is enough.

**Traceback**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/server.py", line 11, in <module>
    import youtube
  File "/usr/src/app/youtube.py", line 9, in <module>
    from youtube_api import YoutubeDataApi
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/__init__.py", line 1, in <module>
    from youtube_api.youtube_api import YoutubeDataApi, YouTubeDataAPI
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/youtube_api.py", line 24, in <module>
    class YouTubeDataAPI:
  File "/opt/venv/lib/python3.8/site-packages/youtube_api/youtube_api.py", line 580, in YouTubeDataAPI
    published_before=datetime.datetime.timestamp(datetime.datetime(3000,1,1)),
OverflowError: timestamp out of range for platform time_t

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version Buster

**Additional context**

**Comment by mabrownnyu** [comment]
This is fixed in the newest update
